apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov
  namespace: sriov-network-operator 
spec:
  ipam: |
    {
      "type": "host-local",
      "subnet": "10.1.1.0/24"
    }
  resourceName: sriov_net
